/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ftpserver;

import beans.UserBean;
import java.awt.Container;
import java.awt.Toolkit;
import services.ManageProfileServices;
import services.ServerThread;
import services.UserActivityServices;

/**
 *
 * @author hp1
 */
public class MainFrame extends javax.swing.JFrame {
    public static Container c;//in this container the panel opens
    public static int activityid;
    public static int userid;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(UserBean objbean) {
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        //toolkit returns object of tool kit and then tool kit class has a method name get screen
        setResizable(false);
        //used to disable minimize button
        c=this.getContentPane();
        //allocates memory to the Container
        //getContentPanel is method of Frame Class
        activityid=UserActivityServices.addLoginTime(objbean.getUserId());
        userid=objbean.getUserId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mnuMaintenance = new javax.swing.JMenu();
        miManageUsers = new javax.swing.JMenuItem();
        miManageProfile = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        miUserReports = new javax.swing.JMenuItem();
        mnuServer = new javax.swing.JMenu();
        miStartServer = new javax.swing.JMenuItem();
        miStopServer = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFile.setText("File");

        miLogout.setText("Log Out");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(miLogout);

        jMenuBar1.add(mnuFile);

        mnuMaintenance.setText("Maintenance");

        miManageUsers.setText("Manage Users");
        miManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManageUsersActionPerformed(evt);
            }
        });
        mnuMaintenance.add(miManageUsers);

        miManageProfile.setText("Manage Profile");
        miManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManageProfileActionPerformed(evt);
            }
        });
        mnuMaintenance.add(miManageProfile);

        jMenuBar1.add(mnuMaintenance);

        mnuReports.setText("Reports");

        miUserReports.setText("Users Reports");
        mnuReports.add(miUserReports);

        jMenuBar1.add(mnuReports);

        mnuServer.setText("Server");
        mnuServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuServerActionPerformed(evt);
            }
        });

        miStartServer.setText("Start Server");
        miStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStartServerActionPerformed(evt);
            }
        });
        mnuServer.add(miStartServer);

        miStopServer.setText("Stop Server");
        mnuServer.add(miStopServer);

        jMenuBar1.add(mnuServer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        UserActivityServices.updateLogoutTime(activityid);
        LoginPage objLP=new LoginPage();
        objLP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miLogoutActionPerformed

    private void miManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManageProfileActionPerformed
        // TODO add your handling code here:
        UserBean objbean=ManageProfileServices.getById(userid);
        c.removeAll();
        c.setVisible(false);
        ManageProfile objMP=new ManageProfile(objbean);
        objMP.setBounds(10,10,600,700);//10,10 is from where panel starts and 600 and 70 is height width;
        c.add(objMP);
        c.setVisible(true);
    }//GEN-LAST:event_miManageProfileActionPerformed

    private void miManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManageUsersActionPerformed
        // TODO add your handling code here:
        c.removeAll();//removes all panel in the container
        c.setVisible(false);//container's visibility hides
        ManageUsers objMU=new ManageUsers();
        objMU.setBounds(10,10,600,700);//10,10 is from where panel starts and 600 and 70 is height width;
        c.add(objMU);
        c.setVisible(true);
    }//GEN-LAST:event_miManageUsersActionPerformed

    private void miStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStartServerActionPerformed
        // TODO add your handling code here:
        ServerThread st=new ServerThread();
        st.run();
    }//GEN-LAST:event_miStartServerActionPerformed

    private void mnuServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuServerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miManageProfile;
    private javax.swing.JMenuItem miManageUsers;
    private javax.swing.JMenuItem miStartServer;
    private javax.swing.JMenuItem miStopServer;
    private javax.swing.JMenuItem miUserReports;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuMaintenance;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuServer;
    // End of variables declaration//GEN-END:variables
}
