/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ftpclient;

import beans.UserBean;
import common.Const;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.net.Socket;
import java.util.TreeMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author hp1
 */
public class Download extends javax.swing.JPanel {
    UserBean objbean=new UserBean();
    TreeMap filesname=new TreeMap<String,String>();
    Socket skt=null;
    DataInputStream dis=null;
    DataOutputStream dos=null;
    int downloadupdateflag=-1;
    /**
     * Creates new form Download
     */
    public Download(UserBean objbean,Socket skt) {
        initComponents();
        this.objbean=objbean;
        tree();
        this.skt=skt;
    }
    public void tree()
    {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Ftp");
        DefaultMutableTreeNode publicfiles = new DefaultMutableTreeNode("Public");
        DefaultMutableTreeNode privatefiles= new DefaultMutableTreeNode("Private");
        DefaultMutableTreeNode username= new DefaultMutableTreeNode(objbean.getUserName());
        DefaultMutableTreeNode othersfiles= new DefaultMutableTreeNode("Others");
        root.add(publicfiles);
        root.add(privatefiles);
        File f1=new File(Const.SERVER_PATH+(objbean.getUserName())+"\\Private");
        File temp1[]=f1.listFiles();
        for(int i=0;i<temp1.length;i++)
        {
            privatefiles.add(new DefaultMutableTreeNode(temp1[i].getName()));
            filesname.put(temp1[i].getName(),temp1[i].toString());
        }
        publicfiles.add(username);
        publicfiles.add(othersfiles);
        f1=new File(Const.SERVER_PATH+(objbean.getUserName())+"\\public");
        File temp2[]=f1.listFiles();
        for(int i=0;i<temp2.length;i++)
        {
            username.add(new DefaultMutableTreeNode(temp2[i].getName()));
            filesname.put(temp2[i].getName(),temp2[i].toString());
        }
        f1=new File(Const.SERVER_PATH);
        File temp3[]=f1.listFiles();
        for(int i=0;i<temp3.length;i++)
        {
            if(!(objbean.getUserName().equals(temp3[i].getName())))
            {
                File f=new File(Const.SERVER_PATH+temp3[i].getName()+"\\public");
                File temp4[]=f.listFiles();
                for(int j=0;j<temp4.length;j++)
                {
                    othersfiles.add(new DefaultMutableTreeNode(temp4[j].getName()));
                    filesname.put(temp4[j].getName(),temp4[j].toString());
                }
            }
        }
        jTreeDownload = new JTree(root);
        jScrollPane1.setViewportView(jTreeDownload);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeDownload = new javax.swing.JTree();
        btnDelete = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        btnRename = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnRenameCancel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtRename = new javax.swing.JTextField();

        jButton5.setText("Cancel");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("File Download");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Download File"));

        jScrollPane1.setViewportView(jTreeDownload);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        btnRename.setText("Rename");
        btnRename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenameActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnRenameCancel.setText("Cancel");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Rename File");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRename, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnRenameCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnDownload)
                        .addGap(28, 28, 28)
                        .addComponent(btnRename)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate)
                    .addComponent(btnRenameCancel))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        /*MainFrame objMF=new MainFrame(objbean,skt);
        objMF.setVisible(true);*/
        MainFrame.c.setVisible(false);
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
            TreePath tp=jTreeDownload.getSelectionPath();
        System.out.println(tp);
        String treefilepath="\\"+tp.getPathComponent(1)+"\\"+tp.getLastPathComponent().toString();
        System.out.println(treefilepath);
        try
        {
            dos=new DataOutputStream(skt.getOutputStream());
            dis=new DataInputStream(skt.getInputStream());
            dos.writeInt(4);
            dos.writeUTF(treefilepath);
            dos.writeUTF("\\"+tp.getPathComponent(1)+"\\"+txtRename.getText().trim());
            /*if(dis.readBoolean())
            {
                 JOptionPane.showMessageDialog(this,"File Deleted","Status",JOptionPane.INFORMATION_MESSAGE);
                 tree();
                 
            }
            else
            {
                 JOptionPane.showMessageDialog(this,"File Not Deleted","Status",JOptionPane.INFORMATION_MESSAGE);
            }*/
        }
        catch(Exception e)
        {
            System.out.println("Exception in rename"+e);
        }
        finally
        {
            try
            {
                dis.close();
                dos.close();
            }
            catch(Exception e)
            {
                System.out.println("Exception in finally of rename"+e);
            }
        }
                                             

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        // TODO add your handling code here:
        TreePath tp=jTreeDownload.getSelectionPath();
        System.out.println(tp);
        String treefile="\\"+tp.getPathComponent(1)+"\\"+tp.getLastPathComponent().toString();
        JFileChooser jf=new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jf.setAcceptAllFileFilterUsed(false);
        jf.showSaveDialog(this);
        File filepath=jf.getSelectedFile();
        String downloadto=filepath.toString();
        System.out.println(downloadto);
        System.out.println(treefile);
        try
        {
            dos=new DataOutputStream(skt.getOutputStream());
            dis=new DataInputStream(skt.getInputStream());
            dos.writeInt(1);
            dos.writeUTF(treefile);
            String wheretodownload=downloadto+"\\"+tp.getLastPathComponent().toString();
            FileOutputStream fos=new FileOutputStream(wheretodownload);
            System.out.println(wheretodownload);
            long size=dis.readLong();
            System.out.println(size);
            byte b[]=new byte[(int)size];
            int c=0;
            System.out.println("Downloading Begins");
            for(int i=0;i<(int)size;i=i+c)
            {
                c=dis.read(b);
                fos.write(b,0,c);
            }
            fos.close();
            System.out.println("File Downloaded");
        }
        catch(Exception e)
        {
            System.out.println("Exception in Download"+e);
        }
        finally
        {
            try
            {
                dis.close();
                dos.close();
            }
            catch(Exception e)
            {
                System.out.println("Exception in fianlly of Download"+e);
            }
        }
        downloadupdateflag=1;
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        TreePath tp=jTreeDownload.getSelectionPath();
        System.out.println(tp);
        String treefilepath="\\"+tp.getPathComponent(1)+"\\"+tp.getLastPathComponent().toString();
        System.out.println(treefilepath);
        try
        {
            dos=new DataOutputStream(skt.getOutputStream());
            dis=new DataInputStream(skt.getInputStream());
            dos.writeInt(3);
            dos.writeUTF(treefilepath);
            if(dis.readBoolean())
            {
                 JOptionPane.showMessageDialog(this,"File Deleted","Status",JOptionPane.INFORMATION_MESSAGE);
                 tree();
            }
            else
            {
                 JOptionPane.showMessageDialog(this,"File Not Deleted","Status",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e)
        {
            System.out.println("Exception in delete"+e);
        }
        finally
        {
            try
            {
                dis.close();
                dos.close();
            }
            catch(Exception e)
            {
                System.out.println("Exception in finally of delete"+e);
            }
        }
                    
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenameActionPerformed
        // TODO add your handling code here:
       TreePath tp=jTreeDownload.getSelectionPath();
        System.out.println(tp);
        String treefilepath="\\"+tp.getPathComponent(1)+"\\"+tp.getLastPathComponent().toString();
        System.out.println(treefilepath);
        try
        {
            dos=new DataOutputStream(skt.getOutputStream());
            dis=new DataInputStream(skt.getInputStream());
            dos.writeInt(4);
            dos.writeUTF(treefilepath);
            dos.writeUTF("\\"+tp.getPathComponent(1)+"\\"+txtRename.getText().trim());
            /*if(dis.readBoolean())
            {
                 JOptionPane.showMessageDialog(this,"File Deleted","Status",JOptionPane.INFORMATION_MESSAGE);
                 tree();
                 
            }
            else
            {
                 JOptionPane.showMessageDialog(this,"File Not Deleted","Status",JOptionPane.INFORMATION_MESSAGE);
            }*/
        }
        catch(Exception e)
        {
            System.out.println("Exception in rename"+e);
        }
        finally
        {
            try
            {
                dis.close();
                dos.close();
            }
            catch(Exception e)
            {
                System.out.println("Exception in finally of rename"+e);
            }
        }
    }//GEN-LAST:event_btnRenameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnRename;
    private javax.swing.JButton btnRenameCancel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTreeDownload;
    private javax.swing.JTextField txtRename;
    // End of variables declaration//GEN-END:variables
}
