/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ftpclient;

import beans.UserBean;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.net.Socket;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import services.Client;

/**
 *
 * @author hp1
 */
public class Upload extends javax.swing.JPanel {

    /**
     * Creates new form Upload
     */
    private Socket skt=null;
    private UserBean objbean;
    private DataInputStream dis=null;
    private DataOutputStream dos=null;
    private String select="";
    private String filepath="";
    public Upload(Socket skt,UserBean objbean) {
        initComponents();
        this.skt=skt;
        this.objbean=objbean;     
    }
    public void upload()
    {
        try
        {
            dos=new DataOutputStream(skt.getOutputStream());
            dis=new DataInputStream(skt.getInputStream());
            dos.writeInt(2);
            dos.writeUTF(select);
            File f=new File(filepath);
            String filename=f.getName();
            dos.writeUTF(filename);
            long size=f.length();
            dos.writeLong(size);
            System.out.println(size);
            System.out.println("Uploading Begins........");
            FileInputStream fis=new FileInputStream(filepath);
            byte b[]=new byte[(int)size];
            int c=0;
            while((c=fis.read(b))!=-1)
            {
                dos.write(b,0,c);
            }		
            System.out.println("File updated Successfully");
            fis.close();
        }
        catch(Exception e)
        {
            System.out.println("Exception in upload button"+e);
        }
        finally
        {    
            try
            {
                dos.close();
                dis.close();
            }
            catch(Exception e)
            {
                System.out.println("Exception in finally of upload"+e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtChooseFile = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        rbPrivate = new javax.swing.JRadioButton();
        rbPublic = new javax.swing.JRadioButton();
        btnUpload = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Upload File"));

        jLabel1.setText("Choose File");

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPrivate);
        rbPrivate.setText("Private");

        buttonGroup1.add(rbPublic);
        rbPublic.setText("Public");

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbPublic)
                        .addGap(26, 26, 26)
                        .addComponent(rbPrivate)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpload)
                    .addComponent(btnBrowse))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPublic)
                    .addComponent(rbPrivate)
                    .addComponent(btnUpload))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        if(rbPublic.isSelected())
            {
                select="\\public";  
            }
            else if(rbPrivate.isSelected())
            {
                select="\\private";
            }
        upload();
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser jf=new JFileChooser();
        jf.showOpenDialog(this);
        File file=jf.getSelectedFile();
        filepath=file.getPath();
        txtChooseFile.setText(filepath);
        if(txtChooseFile.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please Select a file","Empty Field",JOptionPane.INFORMATION_MESSAGE);
            btnBrowse.requestFocus();
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnUpload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbPrivate;
    private javax.swing.JRadioButton rbPublic;
    private javax.swing.JTextField txtChooseFile;
    // End of variables declaration//GEN-END:variables
}
